
export const mockDataList = [
    {
        id: 1,
        lv: 1,
        value: 100,
        desc: 'Already achieved this level',
        progressRate: 100,
        bg: '#728cab',
        count: 1,
    },
    {
        id: 2,
        lv: 2,
        desc: 'still 51 points unlock the next level',
        value: 200,
        progressRate: 100,
        bg: '#66bddc',
        count: 2,

    },
    {
        id: 3,
        lv: 3,
        value: 300,
        desc: 'still 151 points unlock the next level',
        progressRate: 100,
        bg: '#459dde',
        count: 4,

    },
    {
        id: 4,
        lv: 4,
        value: 400,
        desc: 'still 251 points unlock the next level',
        progressRate: 100,
        bg: '#2273ec',
        count: 6,
    },
    {
        id: 5,
        lv: 5,
        value: 500,
        desc: 'still 351 points unlock the next level',
        progressRate: 9,
        bg: '#005fbd',
        status: 'Current',
        count: 7,
    },
    {
        id: 6,
        lv: 6,
        value: 500,
        desc: 'still 451 points unlock the next level',
        progressRate: 9,
        bg: '#01519f',
        status: 'Locked',
        count: 8,
    },
    {
        id: 7,
        lv: 7,
        value: 500,
        desc: 'still 551 points unlock the next level',
        progressRate: 9,
        bg: '#003a72',
        status: 'Locked',
        count: 9,

    },
    {
        id: 8,
        lv: 8,
        value: 500,
        desc: 'still 651 points unlock the next level',
        progressRate: 9,
        bg: '#001c34',
        status: 'Locked',
        count: 14,
    },
];
